# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: |
      sudo apt update
      sudo apt install -y hollywood bpytop || true
    command: |
      echo "✅ Kali environment ready"
      bash
